### PR TITLE
PHPCS code formatting problems solved

### PR DESCRIPTION
**Pull request by fadrian06**

### CODE REVIEW

**Review by n0nag0n — APPROVED** [review]
lgtm, but I don't know why it beautified so differently for you than it did me unless you are forcing sublime to enforce coding standards outside of PSR12

**Comment by fadrian06** [comment]
I have the EditorConfig plugin in Sublime That's why the LSP always respects the 4 spaces and replaces all the tabs that are left there.

**Comment by fadrian06** [comment]
in the source code it does not automatically format unless you commit only the formatting...in this PR I did all the formatting by hand to reduce the size of the lines  since phpcs complains about lines longer than 120 characters

**Comment by fadrian06** [comment]
finally I applied phpcbf but it didn't do anything because almost everything was already formatted

**Pull request merged**
