### PR TITLE
Allow generic middleware filtering using before and after

### PR DESCRIPTION
**Pull request by aleferri**
Add a generic route additional configuration parameter $config with default = []

Allow middleware filtering.

Flight::before( 'dispatchRoute', function(&$param, &$output) {
... //something you want to do before a route get dispatched, $param[0] is the current Route
});

Flight::after( 'dispatchRoute', function(&$param, &$output) {
... //cleanup after the route callback executed, $param[0] is the current Route
});

### CODE REVIEW

**Comment by aleferri** [comment]
Also by remapping the dispatchRoute method is possibile to add lot of custom per route code.
Flight::map('dispatchRoute', function($route, $params) {
     my_cool_function($route, $params);
     my_security_check($route, $params);
     my_context_parsing($route, $params);
     my_init_things_if_route_compatible($route, $params);
     my_add_lots_of_other_params($route, $params);
     Flight::_dispatchRoute($route, $params);
});

**Comment by aleferri** [comment]
Are you still developing it? Anyway contact me back when you are able to do so. In the mean time i will close di PR.

**Comment by marufmax** [comment]
I also need to merge this PR

**Comment by aleferri** [comment]
Where?

**Comment by marufmax** [comment]
i mean, i need the Author to merge this PR

**Pull request closed without merging**
