### PR TITLE
Route alias and phpstan updates

### PR DESCRIPTION
**Pull request by n0nag0n**
Added the ability to set an alias and to rehydrate a url

### CODE REVIEW

**Comment by krmu** [comment]
Jus tried to use urls that has optional params.
It gives out wrong response.
Testing code:
Flight::route('/homepage(/@param)', function ($param) {
    echo 'Homepage';
},false,$alias = 'homepage');
Flight::start();
echo "Url:". Flight::getUrl('homepage');

And respnsones on this I got:
**Url:/homepage(/)**
So, it means that params is being ignored, I guess that bracket should be also removed.

**Comment by krmu** [comment]
Another test on grouped routes. 
Code:
```
Flight::group('/user', function () {
    Flight::group('/all_users', function () {
        Flight::group('/check_user', function () {
            Flight::group('/check_one', function () {
                Flight::route("/normalpath", function () {
                    echo "normalpath";
                },false,"normalpathalias");
            });
        });
    });
});
Flight::start();
echo Flight::getUrl("normalpathalias");
```
Response:
```
500 Internal Server Error
No route found with alias: normalpathalias (0)
#0 D:\xampp\htdocs\core\flight\Engine.php(716): flight\net\Router->getUrlByAlias('normalpathalias', Array)
#1 D:\xampp\htdocs\core\flight\core\Dispatcher.php(225): flight\Engine->_getUrl('normalpathalias')
#2 D:\xampp\htdocs\core\flight\core\Dispatcher.php(164): flight\core\Dispatcher::invokeMethod(Array, Array)
#3 D:\xampp\htdocs\core\flight\core\Dispatcher.php(56): flight\core\Dispatcher::execute(Array, Array)
#4 D:\xampp\htdocs\core\flight\Engine.php(114): flight\core\Dispatcher->run('getUrl', Array)
#5 D:\xampp\htdocs\core\flight\core\Dispatcher.php(225): flight\Engine->__call('getUrl', Array)
#6 D:\xampp\htdocs\core\flight\Flight.php(119): flight\core\Dispatcher::invokeMethod(Array, Array)
#7 D:\xampp\htdocs\core\index.php(19): Flight::__callStatic('getUrl', Array)
#8 {main}
```

**Comment by krmu** [comment]
Grouping is not working with this at all.
```
Flight::group('/user', function () {
    Flight::route('/all_users', function () {
        echo 123;
    },false,'all_users');
 });
Flight::start();
echo Flight::getUrl("all_users");
```
`500 Internal Server Error
No route found with alias: all_users (0)
#0 D:\xampp\htdocs\core\flight\Engine.php(716): flight\net\Router->getUrlByAlias('all_users', Array)
#1 D:\xampp\htdocs\core\flight\core\Dispatcher.php(225): flight\Engine->_getUrl('all_users')
#2 D:\xampp\htdocs\core\flight\core\Dispatcher.php(164): flight\core\Dispatcher::invokeMethod(Array, Array)
#3 D:\xampp\htdocs\core\flight\core\Dispatcher.php(56): flight\core\Dispatcher::execute(Array, Array)
#4 D:\xampp\htdocs\core\flight\Engine.php(114): flight\core\Dispatcher->run('getUrl', Array)
#5 D:\xampp\htdocs\core\flight\core\Dispatcher.php(225): flight\Engine->__call('getUrl', Array)
#6 D:\xampp\htdocs\core\flight\Flight.php(119): flight\core\Dispatcher::invokeMethod(Array, Array)
#7 D:\xampp\htdocs\core\index.php(14): Flight::__callStatic('getUrl', Array)
#8 {main}`

**Review by krmu — COMMENTED** [review]
Jus tried to use urls that has optional params.
It gives out wrong response.
Testing code:
```
Flight::route('/homepage(/@param)', function ($param) {
    echo 'Homepage';
},false,$alias = 'homepage');
Flight::start();
echo "Url:". Flight::getUrl('homepage');
```

And respnsones on this I got:
`Url:/homepage(/)`
So, it means that params is being ignored, I guess that bracket should be also removed.

Another test on grouped routes. 
Code:
```
Flight::group('/user', function () {
    Flight::group('/all_users', function () {
        Flight::group('/check_user', function () {
            Flight::group('/check_one', function () {
                Flight::route("/normalpath", function () {
                    echo "normalpath";
                },false,"normalpathalias");
            });
        });
    });
});
Flight::start();
echo Flight::getUrl("normalpathalias");
```
Response:
```
500 Internal Server Error
No route found with alias: normalpathalias (0)
#0 D:\xampp\htdocs\core\flight\Engine.php(716): flight\net\Router->getUrlByAlias('normalpathalias', Array)
#1 D:\xampp\htdocs\core\flight\core\Dispatcher.php(225): flight\Engine->_getUrl('normalpathalias')
#2 D:\xampp\htdocs\core\flight\core\Dispatcher.php(164): flight\core\Dispatcher::invokeMethod(Array, Array)
#3 D:\xampp\htdocs\core\flight\core\Dispatcher.php(56): flight\core\Dispatcher::execute(Array, Array)
#4 D:\xampp\htdocs\core\flight\Engine.php(114): flight\core\Dispatcher->run('getUrl', Array)
#5 D:\xampp\htdocs\core\flight\core\Dispatcher.php(225): flight\Engine->__call('getUrl', Array)
#6 D:\xampp\htdocs\core\flight\Flight.php(119): flight\core\Dispatcher::invokeMethod(Array, Array)
#7 D:\xampp\htdocs\core\index.php(19): Flight::__callStatic('getUrl', Array)
#8 {main}
```
Grouping is not working with this at all.
```
Flight::group('/user', function () {
    Flight::route('/all_users', function () {
        echo 123;
    },false,'all_users');
 });
Flight::start();
echo Flight::getUrl("all_users");
```
`500 Internal Server Error
No route found with alias: all_users (0)
#0 D:\xampp\htdocs\core\flight\Engine.php(716): flight\net\Router->getUrlByAlias('all_users', Array)
#1 D:\xampp\htdocs\core\flight\core\Dispatcher.php(225): flight\Engine->_getUrl('all_users')
#2 D:\xampp\htdocs\core\flight\core\Dispatcher.php(164): flight\core\Dispatcher::invokeMethod(Array, Array)
#3 D:\xampp\htdocs\core\flight\core\Dispatcher.php(56): flight\core\Dispatcher::execute(Array, Array)
#4 D:\xampp\htdocs\core\flight\Engine.php(114): flight\core\Dispatcher->run('getUrl', Array)
#5 D:\xampp\htdocs\core\flight\core\Dispatcher.php(225): flight\Engine->__call('getUrl', Array)
#6 D:\xampp\htdocs\core\flight\Flight.php(119): flight\core\Dispatcher::invokeMethod(Array, Array)
#7 D:\xampp\htdocs\core\index.php(14): Flight::__callStatic('getUrl', Array)
#8 {main}`

**Comment by n0nag0n** [comment]
@krmu Thanks so much for the feedback! I haven't used this as heavily as some of you other devs out there. I didn't go back and catch optional params so I can build tests against that and figure out why it's not working on group and unit test against that.

**Comment by krmu** [comment]
Thank you for fixing aliases, now we have another issue with params that has numbers inside.
Code:
```
Flight::route('/homepage(/@param1)', function ($param1) {
    echo 'Homepage';
},false,$alias = 'homepage');
Flight::start();
echo "Url:". Flight::getUrl('homepage',array('param1'=>'test'));
```
Response:
`Url:/homepage/1)`

**Comment by n0nag0n** [comment]
@krmu Ok I have grouping fixed and tested against (with your very example) and I fixed the params with numbers in them. I noticed that earlier, but I wasn't sure if numbers were valid as url params. Whelp, they are now :D

**Comment by n0nag0n** [comment]
P.S. You could hop in the chat room if you ever wanted to discuss anything. I usually keep that tab open on my computer. Chat room link is on the Readme

**Comment by krmu** [comment]
Im not sure, but seems that it still wont work. Currently not even allowing to get simple url.

**Comment by krmu** [comment]
> Im not sure, but seems that it still wont work. Currently not even allowing to get simple url.

Currently on my examples getting this:
```
getUrl must be a mapped method. (0)
#0 D:\xampp\htdocs\core\flight\core\Dispatcher.php(229): flight\Engine->__call('getUrl', Array)
#1 D:\xampp\htdocs\core\flight\Flight.php(118): flight\core\Dispatcher::invokeMethod(Array, Array)
#2 D:\xampp\htdocs\core\index.php(8): Flight::__callStatic('getUrl', Array)
#3 {main}

```
Am I missing something?

**Comment by n0nag0n** [comment]
Possibly??? This is me statically calling getUrl() just fine. 
image

And it definitely is a mapped method. 

image

**Comment by krmu** [comment]
Everything works, my bad. Sorry for that.
So currently this monster from:

```php
Flight::group('/user', function () {
    Flight::group('/all_users', function () {
        Flight::group('/check_user', function () {
            Flight::group('/check_one', function () {
                Flight::route("/normalpath", function () {
                    echo "normalpath";
                },false,"normalpathalias");
            });
        });
    });
});
```
Converts into:
```php
normalpath/user/all_users/check_user/check_one/normalpath
```
So it works.

**Comment by krmu** [comment]
Also numbered params works.

**Comment by n0nag0n** [comment]
k, I just need to add some docs to the readme and then it looks like this can go live and be versioned.

**Review by krmu — APPROVED** [review]
Tested with some interesting cases, should be working.

**Pull request merged**
