### PR TITLE
PHP 7.4/8.0/8.1 compatibility

### PR DESCRIPTION
**Pull request by masroore**
- Minimum PHP version: ^7.4|^8.0
- Strict type checking
- All tests updated to PHPUnit ^9

### CODE REVIEW

**Comment by mikecao** [comment]
I think this could be a great fork, but I would like the original to be backward compatible to 4.3, instead of forcing everyone to upgrade.

**Comment by masroore** [comment]
You could create a separate branch for those who require backwards compatibility.

**Comment by ghost** [comment]
@mikecao This is needed to update projects to PHP 8.1. Error related to https://github.com/mikecao/flight/issues/454#issue-1068799709

Can we merge this into master, perhaps creating v2.0 for PHP 7.4 > and keep v1.3.9 for older PHP versions...

**Comment by felipoantonoff** [comment]
> @mikecao This is needed to update projects to PHP 8.1. Error related to [#454 (comment)](https://github.com/mikecao/flight/issues/454#issue-1068799709)
> 
> Can we merge this into master, perhaps creating v2.0 for PHP 7.4 > and keep v1.3.9 for older PHP versions...

I think it's a good idea, created a new version with support for PHP 7.4 or newer like 8.1 and whoever wants old versions can use the previous version or even a branch as already suggested.

In Opencart, releases and tags are used, for example, in the new version under development, Readme warns the PHP version 8 or higher, including the Readme of current versions may even have a warning that those who want older PHP can use Release X.

**Comment by ghost** [comment]
> > @mikecao This is needed to update projects to PHP 8.1. Error related to [#454 (comment)](https://github.com/mikecao/flight/issues/454#issue-1068799709)
> > Can we merge this into master, perhaps creating v2.0 for PHP 7.4 > and keep v1.3.9 for older PHP versions...
> 
> I think it's a good idea, created a new version with support for PHP 7.4 or newer like 8.1 and whoever wants old versions can use the previous version or even a branch as already suggested.
> 
> In Opencart, releases and tags are used, for example, in the new version under development, Readme warns the PHP version 8 or higher, including the Readme of current versions may even have a warning that those who want older PHP can use Release X.

I think this needs to be merged indeed. Composer will take care of versioning and compatibility. Hopefully the maintainer will merge this and create a new release tag 2.0+.

**Comment by pierresh** [comment]
Also, from a "marketing standpoint", it looks better to mention that the PHP minimum version is 7.4 or 8, rather than 5.3 ^^

**Comment by mikecao** [comment]
Hey everyone, I'll merge this soon and create a v2.0 version. Just been really busy.

**Comment by chapani** [comment]
> Hey everyone, I'll merge this soon and create a v2.0 version. Just been really busy.

I am really waiting for this change. I upgraded to 8.1 but the only thing left is flightphp

**Comment by ghost** [comment]
@masroore Is anything extra required for PHP 8.1 for this PR? Did you have a chance testing this on PHP 8.1? Since this request is since May, and PHP 8.1 is released recently.

**Comment by masroore** [comment]
> @masroore Is anything extra required for PHP 8.1 for this PR? Did you have a chance testing this on PHP 8.1? Since this request is since May, and PHP 8.1 is released recently.

@fp07 This PR is now compatible with PHP 8.1. All tests are passing.

**Comment by ghost** [comment]
> > @masroore Is anything extra required for PHP 8.1 for this PR? Did you have a chance testing this on PHP 8.1? Since this request is since May, and PHP 8.1 is released recently.
> 
> @fp07 This PR is now compatible with PHP 8.1. All tests are passing.

Fast work! Thanks, :) @mikecao ready? 👀

**Comment by mu1f407** [comment]
I'm not really happy with this outcome. I think some changes, to be compatible with newest PHP versions, was necessary and I really appreciate possibility of using current version of PHPUnit. But I think this is too much opinionated. There is lot of unneeded changes like strict type checking (breaks #457), typed properties (breaks #456), final classes (breaks possibility of creating stubs in testing) and coding style (I find Yoda conditions harder to read).

I would prefer much lighter upgrade to solve PHP 8.1 compatibility with as little changes as needed and keeping as much compatibility with older PHP versions as possible.

**Pull request merged**
