### PR TITLE
#290 - JSON methods now support encode option/depth

### PR DESCRIPTION
**Pull request by ghost**
JSON methods now support encode option/depth, added missing arguments to json/jsonp method documentation, _json/_jsonp methods now list arguments on individual lines to remain PSR-2 compliant

This adds two new arguments instead of refactoring. In future, should flight decide to release a 2.x.x version number, we should _perhaps_ look at breaking backwards compatibility and replacing the `$encode` argument with an array of encode options whereby the following is true:

`$encode == false` ? Do not encode
`$encode === array() || $encode == true` ? Encode
`isset($encode['option'])` ? Pass option to json_encode parameter 2
`isset($encode['depth'])` ? Pass depth to json_encode parameter 3

Enhancement requested in: https://github.com/mikecao/flight/issues/290

### CODE REVIEW

**Comment by mikecao** [comment]
Thanks, great work!

**Comment by josevh** [comment]
Hi all, this breaks PHP 5.3 compatibility.

I get the following 500 error in response tested on PHP 5.3.3.:
`json_encode() expects at most 2 parameters, 3 given (2)`

Depth was added in 5.5 per: [php.net](http://php.net/manual/en/function.json-encode.php)

I am not sure if the aim is to stay 5.3 compatible.
If not, the README should be updated.

Did I miss something? Should I open an issue?

**Comment by mikecao** [comment]
@josevh Thanks for pointing it out. Yes Flight should be 5.3 compatible. I'll have to roll back the change.

**Comment by ghost** [comment]
@mikecao @josevh By the look of it, we can simply remove the depth addition and leave the "options" values in there. Options was added in 5.3.0. The deeper "options" were added in 5.3.3/5.4.0, but by default we can support all "options" by just passing in an int, as we are now.

I think that's the best compromise, as it maintains full 5.3.0 compatibility and also fixes the original issue.

**Comment by mikecao** [comment]
Fixed in 9c8d492799da73690ae0c370d8cd685148ef09f5.

**Comment by tamtamchik** [comment]
Wow! New minor version! 🎉

**Pull request merged**
