### PR TITLE
Removed all typehints to PHP <7.4 compatibility

### PR DESCRIPTION
**Pull request by fadrian06**
image
image
image

### CODE REVIEW

**Review by n0nag0n — COMMENTED** [review]
So many changes but seems like it'll get the job done. We do have a lot of unit tests in place that are all passing. What do you think @krmu ?

**Comment by krmu** [comment]
> So many changes but seems like it'll get the job done. We do have a lot of unit tests in place that are all passing. What do you think @krmu ?

I will test it out.

**Comment by fadrian06** [comment]
For a moment I was surprised when I changed the © haha... I know it's a massive change but it resolves inconsistencies in which some classes could work in <7.4 and others don't, so removing all the typehint not only maintains consistency but we also support php <7.4... We would have to test until which version works correctly, but I think in 7.0 it would work

**Review by krmu — APPROVED** [review]
Testing worked, but I would like to before merging move to discussion at matrix.

**Comment by n0nag0n** [comment]
We are going to pass on this pull request and instead move forward with static typing on everything as it is stated that this project is 7.4 or greater. We are not going to support older versions of PHP.

**Pull request closed without merging**
