### PR TITLE
feat: method to download files easily

### PR DESCRIPTION
**Pull request by pierresh**
This PR adds the method `download()` to download easily a file from the server.

Example:
```php
$file = 'path/to/file.txt';

Flight::download($path);
```

### CODE REVIEW

**Comment by n0nag0n** [comment]
Thanks for creating this PR. When I get around to it, I'll have to change a bit of this code to conform to the contribution requirements (unit testing, syntax requirements, etc). For now I assume you're good with just keeping this as a `Flight::map('download', ...);` method in your project correct?

**Comment by pierresh** [comment]
Yes, I can use `map()` for time being, thanks!

**Comment by n0nag0n** [comment]
Wanna look this over in case I missed anything?

**Comment by pierresh** [comment]
I checked the code and ran the test, it looks good to me, thanks!

**Review by n0nag0n — APPROVED** [review]

**Pull request merged**
