### PR TITLE
added plain stream() method

### PR DESCRIPTION
**Pull request by n0nag0n**
Simplified streaming methods with `stream()` route method

### CODE REVIEW

**Review by fadrian06 — APPROVED** [review]

**Comment by fadrian06** [comment]
In a while I'll run the tests just in case hehe, right now I don't have electricity

**Comment by fadrian06** [comment]
PHPUnit 9.6.18 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.4.33
Configuration: C:\xampp\htdocs\libs\flight\phpunit.xml
Random Seed:   1712965480

...............................................................  63 / 288 ( 21%)
.................................................F

Time: 00:01.854, Memory: 10.00 MB

There was 1 failure:

1) tests\ResponseTest::testResponseBodyCallbackGzip
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'H4sIAAAAAAAAAytJLS4BAAx+f9gEAAAA'
+'H4sIAAAAAAAACitJLS4BAAx+f9gEAAAA'

C:\xampp\htdocs\libs\flight\tests\ResponseTest.php:285
phpvfscomposer://C:\xampp\htdocs\libs\flight\vendor\phpunit\phpunit\phpunit:106
C:\xampp\htdocs\libs\flight\vendor\bin\phpunit:118

FAILURES!
Tests: 113, Assertions: 206, Failures: 1.

**Comment by fadrian06** [comment]
PHPUnit 9.6.18 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.17
Configuration: C:\xampp\htdocs\libs\flight\phpunit.xml
Random Seed:   1712965580

...............................................................  63 / 288 ( 21%)
......................................F

Time: 00:00.733, Memory: 8.00 MB

There was 1 failure:

1) tests\ResponseTest::testResponseBodyCallbackGzip
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'H4sIAAAAAAAAAytJLS4BAAx+f9gEAAAA'
+'H4sIAAAAAAAACitJLS4BAAx+f9gEAAAA'

C:\xampp\htdocs\libs\flight\tests\ResponseTest.php:285
C:\xampp\htdocs\libs\flight\vendor\bin\phpunit:122

FAILURES!
Tests: 102, Assertions: 152, Failures: 1.

**Review by fadrian06 — CHANGES_REQUESTED** [review]
There's a test fail on my machine

**Comment by n0nag0n** [comment]
Huh, I wonder if that's a difference between windows vs linux implementation of gzip? Just double check and run `composer update` On your recent PR I had an error in PHPStan and I couldn't make it go away until I updated (not realizing it was out of date), and updated whatever packages you have for php/gzip. Just in case they are out of date. It's really weird it's only mixing up two characters in the middle.

**Comment by fadrian06** [comment]
I guess I'll make an assert for windows and another for unix xD

**Comment by fadrian06** [comment]
I'm checking phpstan right now

**Comment by fadrian06** [comment]
image
image
image

**Review by fadrian06 — APPROVED** [review]

**Pull request merged**
