### PR TITLE
fix wrong type usage

### PR DESCRIPTION
**Pull request by saschanos**

### CODE REVIEW

**Comment by saschanos** [comment]
@mikecao, can you merge this fix? :)

**Comment by n0nag0n** [comment]
Merged into n0nag0n/flight in case your interested.

**Comment by saschanos** [comment]
@mikecao, what about the original project? :)

**Comment by n0nag0n** [comment]
I've reached out via several methods to Mike. I just don't want to see a good project go unmaintained if people use it and appreciate it. He's a good guy, just busy I'm sure.

**Comment by n0nag0n** [comment]
It's on packagist if you need to update. https://packagist.org/packages/n0nag0n/flight

**Pull request merged**
